/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcordesRouteImport } from './routes/acordes'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as EscucharRouteImport } from './routes/escuchar'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LetrasRouteImport } from './routes/letras'
import { Route as SetlistsRouteImport } from './routes/setlists'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcordesRoute = AcordesRouteImport.update({
  id: '/acordes',
  path: '/acordes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const EscucharRoute = EscucharRouteImport.update({
  id: '/escuchar',
  path: '/escuchar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LetrasRoute = LetrasRouteImport.update({
  id: '/letras',
  path: '/letras',
  getParentRoute: () => rootRouteImport,
} as any)
const SetlistsRoute = SetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acordes': typeof AcordesRoute
  '/equipo': typeof EquipoRoute
  '/escuchar': typeof EscucharRoute
  '/estadisticas': typeof EstadisticasRoute
  '/favoritos': typeof FavoritosRoute
  '/letras': typeof LetrasRoute
  '/setlists': typeof SetlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acordes': typeof AcordesRoute
  '/equipo': typeof EquipoRoute
  '/escuchar': typeof EscucharRoute
  '/estadisticas': typeof EstadisticasRoute
  '/favoritos': typeof FavoritosRoute
  '/letras': typeof LetrasRoute
  '/setlists': typeof SetlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acordes': typeof AcordesRoute
  '/equipo': typeof EquipoRoute
  '/escuchar': typeof EscucharRoute
  '/estadisticas': typeof EstadisticasRoute
  '/favoritos': typeof FavoritosRoute
  '/letras': typeof LetrasRoute
  '/setlists': typeof SetlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acordes'
    | '/equipo'
    | '/escuchar'
    | '/estadisticas'
    | '/favoritos'
    | '/letras'
    | '/setlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acordes'
    | '/equipo'
    | '/escuchar'
    | '/estadisticas'
    | '/favoritos'
    | '/letras'
    | '/setlists'
  id:
    | '__root__'
    | '/'
    | '/acordes'
    | '/equipo'
    | '/escuchar'
    | '/estadisticas'
    | '/favoritos'
    | '/letras'
    | '/setlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcordesRoute: typeof AcordesRoute
  EquipoRoute: typeof EquipoRoute
  EscucharRoute: typeof EscucharRoute
  EstadisticasRoute: typeof EstadisticasRoute
  FavoritosRoute: typeof FavoritosRoute
  LetrasRoute: typeof LetrasRoute
  SetlistsRoute: typeof SetlistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acordes': {
      id: '/acordes'
      path: '/acordes'
      fullPath: '/acordes'
      preLoaderRoute: typeof AcordesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escuchar': {
      id: '/escuchar'
      path: '/escuchar'
      fullPath: '/escuchar'
      preLoaderRoute: typeof EscucharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letras': {
      id: '/letras'
      path: '/letras'
      fullPath: '/letras'
      preLoaderRoute: typeof LetrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setlists': {
      id: '/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof SetlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcordesRoute: AcordesRoute,
  EquipoRoute: EquipoRoute,
  EscucharRoute: EscucharRoute,
  EstadisticasRoute: EstadisticasRoute,
  FavoritosRoute: FavoritosRoute,
  LetrasRoute: LetrasRoute,
  SetlistsRoute: SetlistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
